services:
  - type: web
    name: meu-bot-instagram
    env: python
    plan: free
    buildCommand: docker build -t meu-bot-instagram .
    startCommand: docker run -e TELEGRAM_TOKEN=$TELEGRAM_TOKEN -e IG_USERNAME=$IG_USERNAME -e IG_PASSWORD=$IG_PASSWORD -e WEBHOOK_URL=$WEBHOOK_URL -p 8443:8443 meu-bot-instagram
    envVars:
      - key: TELEGRAM_TOKEN
        fromSecret: TELEGRAM_TOKEN
      - key: IG_USERNAME
        fromSecret: IG_USERNAME
      - key: IG_PASSWORD
        fromSecret: IG_PASSWORD
      - key: WEBHOOK_URL
        fromSecret: WEBHOOK_URL
